### ISSUE TITLE
Not working on Android <9

### ISSUE THREAD

**Issue by bartdeveloper** [mibrito707/cordova-plugin-secure-storage-echo#56]
This plugin works great on emulator with Android 9 and 10 but on Android 7 & 8 returns this error:

```
2020-10-08 15:34:51.255 4370-5975/************** E/SecureStorage: Encrypt failed :
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at com.crypho.plugins.RSA.loadKey(RSA.java:113)
        at com.crypho.plugins.RSA.runCipher(RSA.java:95)
        at com.crypho.plugins.RSA.encrypt(RSA.java:37)
        at com.crypho.plugins.SecureStorage$2.run(SecureStorage.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by Abhishek-Kanitkar** [comment]
@bartdeveloper  did you face this issue on a real device with Android version < 9 ?

**Comment by a-sac** [comment]
Getting the same error `Error Error: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference` on a xiaomi Mi 9T, Android version 10

**Comment by a-sac** [comment]
Found this: https://github.com/adorsys/secure-storage-android/issues/62
Maybe it helps solving the issue
