### ISSUE TITLE
I/SecureStorage: Checking encryption keys failed.

### ISSUE THREAD

**Issue by ajprok** [mibrito707/cordova-plugin-secure-storage-echo#64]
Hi,

The first time (fresh installation) I run my cordova app in my phone, I get the error `I/SecureStorage: Checking encryption keys failed.`. However, the second time (after previous installation which had error), the app works without any such error. I have given more troubleshooting details below:

Phone: Samsung Galaxy M01 Core - Android Go Edition - Android 10
 defaultMinSdkVersion=22
 defaultTargetSdkVersion=29
 defaultCompileSdkVersion=29

`I/SecureStorage: Checking encryption keys failed.
    java.lang.Exception: KeyStore doesn't contain alias: com.test.app.xyz
        at com.crypho.plugins.AbstractRSA.loadKey(AbstractRSA.java:75)
        at com.crypho.plugins.RSA.isEntryAvailable(RSA.java:24)
        at com.crypho.plugins.AbstractRSA.encryptionKeysAvailable(AbstractRSA.java:25)
        at com.crypho.plugins.SecureStorage.execute(SecureStorage.java:106)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)`

I suspect it may be some issue related to **asynchronous events**. The first time, SecureStorage executes the command, before the keystore is able to create & return the alias. This leads to the error.

Kindly look into this matter. Thanks.

Ajit

**Comment by ajprok** [comment]
Sorry. Realised that the above message was just a warning.
